language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kausjethdoc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kausjethdoc/docker-react npm run test
